sudo: required

language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

before_install:
  - sudo service mysql stop || echo "mysql not stopped"
  - docker run --name mysql-container --rm  -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 -d mysql:5.7

install:
  - composer install

script:
  - vendor/bin/phpunit
